export default {
  otherFiles: 'Other files', otherIntro: 'Additional Markdown by week, including teacher materials. Available locally only.', fileLoading: 'Loading files…', fileError: 'Could not load files.', fileOpen: 'Read file', sourceFile: 'Source file', backWeek: 'Back to week overview',
  showNotes: 'Teacher view', hideNotes: 'Hide notes', speakerNotes: 'Speaker notes', notesLoading: 'Loading notes…', notesError: 'Could not load notes. Open the lesson through localhost.', retryNotes: 'Try again', noNotes: 'No notes for this slide.',
  title: 'Explore', accent: 'the lessons', kicker: 'Foundation · course materials',
  intro: 'From the first design decision to a substantiated security dossier. Choose a week, open a lesson and read at your own pace.',
  week: 'Week', block: 'Block', lessons: 'lessons', minutes: '90 minutes', draft: 'First draft',
  chooseWeek: 'Lessons by week',
  open: 'View lesson', openWeek: 'Explore this week', pending: 'In development',
  presentation: 'Lesson presentation', chooseSlide: 'Go to slide', slide: 'Slide',
  previousSlide: 'Previous slide', nextSlide: 'Next slide', fullscreen: 'Full screen', exitFullscreen: 'Exit full screen',
  fullscreenError: 'Full screen is unavailable in this browser. You can continue using the slides here.',
  slideKeys: 'Click inside the slide and use ← / → to navigate. Home / End goes to the first / last slide.',
  scrollSlide: 'This slide has more content: scroll inside it to read everything.',
  pendingText: 'The lesson files for this week are still being developed.',
  all: 'All lessons', search: 'Find a lesson', placeholder: 'Search Dutch titles, e.g. assets, governance or cultuur',
  noResults: 'No lessons found. Try a different search term.', clear: 'Clear search',
  contents: 'In this lesson', part: 'Section', attachments: 'Worksheets & cases',
  attachmentsIntro: 'Student materials to use alongside the lessons.', previous: 'Previous lesson', next: 'Next lesson',
  print: 'Print / save as PDF', languageNote: 'Course materials are in Dutch and are still in development.',
  conceptNote: 'First draft · These materials may change. Your lecturer will confirm practical arrangements.',
  back: 'Back to', reading: 'Read lesson', review: 'Local review', attachment: 'Student material',
  weeks: [
    { n: 1, title: 'Mindset & culture', goal: 'Why & who' },
    { n: 2, title: 'Threats & attackers', goal: 'The outside world' },
    { n: 3, title: 'Governance & organisation', goal: 'Rules, supply chains & response' },
    { n: 4, title: 'Design & development', goal: 'Requirements & lifecycle' },
  ],
}
