export default {
  otherFiles: 'Overige bestanden', otherIntro: 'Aanvullende Markdown per week, inclusief docentmateriaal. Alleen lokaal beschikbaar.', fileLoading: 'Bestanden laden…', fileError: 'Bestanden konden niet worden geladen.', fileOpen: 'Lees bestand', sourceFile: 'Bronbestand', backWeek: 'Terug naar weekoverzicht',
  showNotes: 'Notities tonen', hideNotes: 'Notities verbergen', speakerNotes: 'Speaker notes', notesLoading: 'Notities laden…', notesError: 'Notities konden niet worden geladen. Open de les via localhost.', retryNotes: 'Opnieuw proberen', noNotes: 'Geen notities bij deze slide.',
  title: 'De lessen', accent: 'bij elkaar', kicker: 'Fundament · lesmateriaal',
  intro: 'Van de eerste ontwerpkeuze tot een onderbouwd securitydossier. Kies een week, open een les en lees in je eigen tempo.',
  week: 'Week', block: 'Blok', lessons: 'lessen', minutes: '90 minuten', draft: 'Eerste versie',
  chooseWeek: 'Lessen per week',
  open: 'Bekijk de les', openWeek: 'Bekijk deze week', pending: 'In ontwikkeling',
  presentation: 'Lespresentatie', chooseSlide: 'Ga naar slide', slide: 'Slide',
  previousSlide: 'Vorige slide', nextSlide: 'Volgende slide', fullscreen: 'Volledig scherm', exitFullscreen: 'Verlaat volledig scherm',
  fullscreenError: 'Volledig scherm is niet beschikbaar in deze browser. Je kunt hier verder bladeren.',
  slideKeys: 'Klik in de slide en gebruik ← / → om te bladeren. Home / End gaat naar de eerste / laatste slide.',
  scrollSlide: 'Deze slide heeft meer inhoud: scroll binnen de slide om alles te lezen.',
  pendingText: 'De lesbestanden voor deze week worden nog uitgewerkt.',
  all: 'Alle lessen', search: 'Zoek een les', placeholder: 'Bijvoorbeeld assets, governance of cultuur',
  noResults: 'Geen lessen gevonden. Probeer een ander zoekwoord.', clear: 'Wis zoekopdracht',
  contents: 'In deze les', part: 'Onderdeel', attachments: 'Werkbladen & casussen',
  attachmentsIntro: 'Studentmateriaal om naast de lessen te gebruiken.', previous: 'Vorige les', next: 'Volgende les',
  print: 'Print / bewaar als PDF', languageNote: 'Het lesmateriaal is Nederlandstalig en in ontwikkeling.',
  conceptNote: 'Eerste versie · Dit materiaal kan nog worden aangescherpt. Praktische afspraken lopen via je docent.',
  back: 'Terug naar', reading: 'Les lezen', review: 'Lokaal reviewen', attachment: 'Studentmateriaal',
  weeks: [
    { n: 1, title: 'Mindset & cultuur', goal: 'Waarom & wie' },
    { n: 2, title: 'Dreigingen & aanvallers', goal: 'De boze buitenwereld' },
    { n: 3, title: 'Governance & organisatie', goal: 'Regels, ketens & respons' },
    { n: 4, title: 'Ontwerpen & bouwen', goal: 'Requirements & lifecycle' },
  ],
}
