export default {
  title: 'Work in', accent: 'development', kicker: 'Local workspace',
  intro: 'Explore lessons, collect actions and read drafts. One place to develop and review the materials.',
  local: 'Local only · excluded from the public website',
  week: 'Week', project: 'Project outline', opf: 'OPF', opfHint: 'Local preparation of the education programme.',
  lessonMaterials: 'Course materials',
  latestActions: 'Open actions', latestDrafts: 'Recently updated drafts', openReviews: 'Documents awaiting review',
  noActions: 'No open actions.', noDrafts: 'No drafts yet.', noReviews: 'All documents have been reviewed.',
  allItems: 'View all', updated: 'Updated', reviewStatus: { open: 'Awaiting review', changes: 'Changes requested', stale: 'Source changed' },
  cards: [
    { path: '/lessen', title: 'Lessons', text: 'Browse the weeks and view each lesson as slides.', color: 'var(--w1)' },
    { path: '/acties', title: 'Actions', text: 'Add actions, check them off and save them in ACTIES.md.', color: 'var(--w2)' },
    { path: '/concepten', title: 'Drafts', text: 'Read the Markdown files from draft_inprogress.', color: 'var(--w3)' },
    { path: '/review', title: 'Reviews', text: 'Read teacher notes and save feedback on each lesson section.', color: 'var(--w4)' },
  ],
  open: 'Open', actions: 'Actions', drafts: 'Drafts', loading: 'Loading…', loadError: 'Could not load. Open this workspace via localhost or 127.0.0.1.',
  source: 'Source', newAction: 'New action', add: 'Add', save: 'Save to ACTIES.md', saving: 'Saving…',
  saved: 'Saved to ACTIES.md.', unsaved: 'Unsaved changes', clean: 'Everything saved',
  edit: 'Edit Markdown', actionHint: 'New actions are saved immediately when added. After checking off actions or editing the Markdown, click Save. You can also edit this file directly and share it through Git.',
  saveError: 'Could not save. The file may have changed elsewhere. Copy your text and reload; your input remains here.',
  leave: 'You have unsaved actions. Leave this page?',
  draftHint: 'Read-only draft viewer. Edit the original files in your editor. Materials are in Dutch; HTML and PDF files remain in the source directory.',
  files: 'Markdown files', empty: 'No actions yet. Add one above.',
}
