export default {
  title: 'Samen in', accent: 'ontwikkeling', kicker: 'Lokale werkplek',
  intro: 'Bekijk lesmateriaal, verzamel acties en lees de concepten. Alles voor het ontwikkelen en reviewen bij elkaar.',
  local: 'Alleen lokaal · niet op de publieke website',
  week: 'Week', project: 'Projectopzet', opf: 'OPF', opfHint: 'Lokale voorbereiding van het onderwijsprogramma.',
  lessonMaterials: 'Lesmateriaal',
  weekOverview: 'Weekoverzicht',
  weekOverviewHint: 'De gewenste weekopbouw, de huidige stand en het OPF met de impact van de voorgestelde wijzigingen. De documenten zijn Nederlandstalig.',
  weekOverviewLinks: [
    { file: 'weekopbouw-gewenst.md', label: 'Gewenste weekopbouw & impact' },
    { file: 'weekopbouw-huidige-stand.md', label: 'Huidige stand ter vergelijking' },
    { file: 'opf-v0.2-leesbaar.md', label: 'OPF v0.2 · leesbare versie' },
    { file: 'opf-impact-weekopbouw-mark.md', label: 'OPF · impact wijzigingen Mark' },
  ],
  latestActions: 'Open acties', latestDrafts: 'Laatst gewijzigde concepten', openReviews: 'Documenten met open review',
  noActions: 'Geen open acties.', noDrafts: 'Nog geen concepten.', noReviews: 'Alle documenten zijn beoordeeld.',
  allItems: 'Bekijk alles', updated: 'Gewijzigd', reviewStatus: { open: 'Nog te reviewen', changes: 'Aanpassingen nodig', stale: 'Bron gewijzigd' },
  cards: [
    { path: '/lessen', title: 'Lessen', text: 'Blader door de weken en bekijk iedere les als slides.', color: 'var(--w1)' },
    { path: '/acties', title: 'Acties', text: 'Voeg acties toe, vink ze af en sla ze op in ACTIES.md.', color: 'var(--w2)' },
    { path: '/concepten', title: 'Concepten', text: 'Lees de Markdown-bestanden uit draft_inprogress.', color: 'var(--w3)' },
    { path: '/review', title: 'Reviews', text: 'Bekijk docentnotities en bewaar feedback per lesonderdeel.', color: 'var(--w4)' },
    { path: '/weekoverzicht', title: 'Weekoverzicht', text: 'Bekijk de gewenste opbouw van alle twintig weken en de gevolgen voor lessen en mijlpalen.', color: 'var(--w1)' },
  ],
  open: 'Open', actions: 'Acties', drafts: 'Concepten', loading: 'Laden…', loadError: 'Laden mislukt. Open deze werkplek via localhost of 127.0.0.1.',
  source: 'Bron', newAction: 'Nieuwe actie', add: 'Toevoegen', save: 'Bewaar in ACTIES.md', saving: 'Opslaan…',
  saved: 'Opgeslagen in ACTIES.md.', unsaved: 'Niet-opgeslagen wijzigingen', clean: 'Alles opgeslagen',
  edit: 'Markdown aanpassen', actionHint: 'Nieuwe acties worden bij toevoegen meteen opgeslagen. Vink je acties af of bewerk je de Markdown, klik dan op Bewaar. Dit bestand kan ook rechtstreeks in je editor worden aangepast en via Git worden gedeeld.',
  saveError: 'Opslaan mislukt. Het bestand kan elders zijn gewijzigd. Kopieer je tekst en herlaad; je invoer blijft hier staan.',
  leave: 'Er zijn niet-opgeslagen acties. Wil je deze pagina verlaten?',
  draftHint: 'Leesweergave van concepten. Bewerk de originele bestanden in je editor. Het materiaal is Nederlandstalig; HTML- en PDF-bestanden blijven in de bronmap.',
  files: 'Markdown-bestanden', empty: 'Nog geen acties. Voeg hierboven een actie toe.',
}
